# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('content', models.TextField(verbose_name='본문')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
    ]
