# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Post',
        ),
    ]
